// react-three-dots/src/App.js
import "./App.css";
import React, { useState, useEffect } from "react";
//
import Admin from "./components/Admin";
import Guest from "./components/Guest";

function App() {
  const [msg, setMsg] = useState("");

  useEffect(() => {
    fetch("http://localhost:7000/users")
      .then((res) => res.json())
      .then((data) => setMsg(data.msg));
  }, []);

  return (
    <div id="app">
      <h1>Welcome Three Dots!</h1>
      <pre>{msg}</pre>
      <div>
        <div>
          <Admin />
        </div>
        <div>
          <Guest />
        </div>
      </div>
    </div>
  );
}

export default App;

// svelte-three-dots/src/App.svelte
<script>
const fetchImage = (async () => {
	const response = await fetch('http://localhost:7000/users')
	return await response.json()
})()
</script>

<div id="app">
	<h1>Welcome Three Dots!</h1>
	{#await fetchImage}
	<pre>...waiting</pre>
	{:then data}
	<pre>{data.msg}</pre>
	{:catch error}
	<pre>An error occurred!</pre>
	{/await}
</div>

<style>
	* {
	  box-sizing: border-box;
	}

	body {
	  margin: 0px;
	  padding: 0px;
	}

	#app {
		margin-top: 4rem;
	}
</style>
